first_name = input("input your first name: ")
last_name = input("input your last name: ")
birth_year = int(input("input your birth year(e.g., 2000): "))
this_year = int(input("input this year(e.g., 2020): "))
gender = input("input your gender(e.g., male or female): ")
school_id = int(input("input your school-id(e.g., 20200015): "))
print("My name is", first_name, last_name+".")
print("I am", this_year-birth_year, "years old", gender+".")
print("And I am a student of Data technology major in Myongji University!")
print("My student id is", school_id, "and I am happy to join this major!")
